[build]
  publish = "dist"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "18"
  # Firebase Configuration - Replace with your actual values
  VITE_FIREBASE_API_KEY = "AIzaSyBCgGrWvoQw_7gooTQHZpYcqhEEk8-qbf0"
  VITE_FIREBASE_AUTH_DOMAIN = "weirdy-a9be1.firebaseapp.com"
  VITE_FIREBASE_PROJECT_ID = "weirdy-a9be1"
  VITE_FIREBASE_STORAGE_BUCKET = "weirdy-a9be1.firebasestorage.app"
  VITE_FIREBASE_SENDER_ID = "109828981298"
  VITE_FIREBASE_APP_ID = "1:109828981298:web:9bd0476808d333c65bf22b"

[[headers]]
  for = "/manifest.webmanifest"
  [headers.values]
    Content-Type = "application/manifest+json"

[[headers]]
  for = "/sw.js"
  [headers.values]
    Content-Type = "application/javascript"
    Service-Worker-Allowed = "/"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Cache static assets
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Cache images
[[headers]]
  for = "/*.png"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "/*.jpg"
  [headers.values]
    Cache-Control = "public, max-age=31536000"
