[build]
  publish = "dist"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "18"
  # Firebase Configuration - Replace with your actual values
  VITE_FIREBASE_API_KEY = "your-api-key-here"
  VITE_FIREBASE_AUTH_DOMAIN = "your-project.firebaseapp.com"
  VITE_FIREBASE_PROJECT_ID = "your-project-id"
  VITE_FIREBASE_STORAGE_BUCKET = "your-project.appspot.com"
  VITE_FIREBASE_SENDER_ID = "your-sender-id"
  VITE_FIREBASE_APP_ID = "your-app-id"

[[headers]]
  for = "/manifest.webmanifest"
  [headers.values]
    Content-Type = "application/manifest+json"

[[headers]]
  for = "/sw.js"
  [headers.values]
    Content-Type = "application/javascript"
    Service-Worker-Allowed = "/"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Cache static assets
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Cache images
[[headers]]
  for = "/*.png"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "/*.jpg"
  [headers.values]
    Cache-Control = "public, max-age=31536000"
